os: linux
dist: focal  # Ubuntu 20.04 build environment

git:
  submodules: true

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.9-dev"
    - python: "nightly"

before_install:
  - sudo apt-get install g++
  - sudo apt-get install cmake
  - sudo apt-get install bison
  - sudo apt-get install flex
  - sudo apt-get install python2-minimal

install:
  - pip install -r requirements.txt

script:
  - python build_scripts/travis_script.py
